version: '3.8'
services:
  graphql-api:
    build: .
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - DB_PATH=/app/database/ip_details.sqlite
    volumes:
      - ./database:/app/database
    depends_on:
      - sqlite-container

  sqlite-container:
    image: alpine:latest
    volumes:
      - sqlite_data:/app/database
    command: tail -f /dev/null
volumes:
  sqlite_data: