// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type IPDetails struct {
	UUID         string    `json:"uuid"`
	IPAddress    string    `json:"ipAddress"`
	ResponseCode string    `json:"responseCode"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type Mutation struct {
}

type Query struct {
}
