package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"spamhaus-wrapper/graph/generated"
	"spamhaus-wrapper/graph/model"
)

// UpdateIPDetails is the resolver for the updateIPDetails field.
func (r *mutationResolver) UpdateIPDetails(ctx context.Context, ips []string) ([]*model.IPDetails, error) {
	return r.IPDetailsRepo.UpdateMultipleIPDetails(ctx, ips)
}

// GetIPDetails is the resolver for the getIPDetails field.
func (r *queryResolver) GetIPDetails(ctx context.Context, ip string) (*model.IPDetails, error) {
	return r.IPDetailsRepo.GetIPDetails(ip)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
